//#pragma once
//
//void init();
//void resize(int width, int height);
//void draw();
//void specialkey(int key, int x, int y); //카메라의 시점을 바꾸는 키를 입력받기 위한 함수
//void keyboard(unsigned char key, int x, int y); //기능을 위한 키보드 callback 함수
//void mouse(int botton, int state, int x, int y);
//void motion(int x, int y);
//void sub_menu_function(int option);
//void main_menu_function(int option);
//void idle();
//void draw_axis();
//
//void draw_Printer_up();
//void draw_Printer_up2();
//void draw_Printer_front();
//void draw_Printer_front1();
//void draw_Printer_front2();
//void draw_Printer_front3();
//void draw_Printer_front4();
//void draw_Printer_front4_2();
//void draw_Printer_front4_3();
//void draw_Printer_front4_4();
//void draw_Printer_front5();
//void draw_Printer_front5_2();
//void draw_Printer_front5_3();
//void draw_Printer_front5_4();
//void draw_Printer_front6();
//void draw_Printer_right1();
//void draw_Printer_right2();
//void draw_Printer_right3();
//void draw_Printer_right4();
//void draw_Printer_right5();
//void draw_Printer_left();
//void draw_Printer_left2();
//void draw_Printer_left3();
//void draw_Printer_back1();
//void draw_Printer_back2();
//void draw_Printer_back2_2();
//void draw_Printer_back2_3();
//void draw_Printer_back2_4();
//void draw_Printer_back2_5();
//void draw_Printer_back2_5_1();
//void draw_Printer_back2_5_2();
//void draw_Printer_back2_5_3();
//void draw_Printer_back2_6();
//void draw_Printer_back3();
//void draw_Printer_back3_2();
//void draw_Printer_back3_3();
//void draw_Printer_back3_4();
//void draw_Printer_down();
//void draw_Printer_In();
//void draw_Printer_In2();
//void draw_Ink_can();
//void draw_Ink_can_cover();
//void draw_Ink_can_cover2();
//void draw_Ink_can_down_cover();
//void draw_Ink_down_Color(int Ink_down_Color);
//void draw_Ink_Red(float Red);
//void draw_Ink_Yellow(float Yellow);
//void draw_Ink_Blue(float Blue);
//void draw_Ink_Black(float Black);
//void draw_MyPrinter_Up();
//void draw_MyPrinter_Right();
//void draw_MyPrinter_Front();
//void draw_MyPrinter_Left();
//void draw_MyPrinter_Down();
//void draw_MyPrinter_Back();
//void draw_MyPrinter();
//void draw_MyPrinter_In();
//void draw_Quad();
//void draw_skybox();
//void draw_MyInk();
//void draw_A4();
//void draw_text();
//void draw_Ink_line();
//void draw_Ink_line2();
//void draw_Ink_line3();
//void draw_Ink_line4();
//void Refill_A4();
//void Act_Printing();
//void Display_Ink();
//void DIsplay_Ink2();
//void draw_Table_1();
//void draw_Table_2();
//void draw_Table();
//void draw_Disk();